### ISSUE TITLE
I used it in lazyvim and it didn't work.

### ISSUE THREAD

**Issue by qinjianwei** [gaoDean/autolist.nvim#88]
[20240723073605.webm](https://github.com/user-attachments/assets/e502e8d8-9311-4080-997a-dfd27998d29b)

**Comment by JoshPaulie** [comment]
It sort of worked for me, with regular lazy.nvim. Only when using `o` or `O` to add a new line. not so much with `<CR>`. `<CR>` didn't work for either bullet or numbered list

**Comment by HanifCarroll** [comment]
I'm getting the same issue with the LazyVim. It worked fine when I was using only lazy.nvim.  Calling the command manually from the command menu works, so there must be something shadowing the key map.

Edit: It's autopairs. Disabling it allows autolist to work correctly.

Double Edit: Using ultimate-autopair instead of nvim-autopairs works.
